### PR TITLE
add the xml import/export function using Rapidxml

### PR DESCRIPTION
**Pull request by gudongfeng**

### CODE REVIEW

**Comment by asolis** [comment]
I merged your pull request and also added the rules to Cmake. Fixed a couple of compilation errors due to different OS. Btw, what's the name of this format? If you will like to add details to the wiki about it could be nice. I am adding you as contributor in the Readme file :)

**Comment by gudongfeng** [comment]
This is a simplify version of [viper](http://viper-toolkit.sourceforge.net/docs/file/). Sure, I can add more details to the wiki page,

**Comment by gudongfeng** [comment]
Can you please grant me the access to your wiki page? Thank you!

**Comment by asolis** [comment]
You should be able to edit the wiki pages by now.

**Comment by gudongfeng** [comment]
I finished editing the wiki page, feel free to check/edit it . @asolis

**Comment by asolis** [comment]
It's good thanks! you could add the command line options for using the xml format (read/write) in [this page](https://github.com/asolis/Annotate/wiki/Command-Line-Options)

**Comment by gudongfeng** [comment]
finished! :+1:

**Pull request merged**
