### PR TITLE
add the xml file output/input option

### PR DESCRIPTION
**Pull request by gudongfeng**
add the xml output file option for the extract and annotate program.

### CODE REVIEW

**Comment by asolis** [comment]
@frankgu, this looks great!. Any particular reason why u didn't use the xml parser reader of OpenCV? I think it could be nicer if no extra dependencies are needed.... 
what do you think?

**Comment by gudongfeng** [comment]
@asolis Oops, I thought OpenCV didn't have this kind of stuff, I will change it to OpenCV

**Comment by asolis** [comment]
It depends what are the requirements for the final format. I am not sure if OpenCV could handle it, that's why I am asking you. I know that OpenCV has an XML format.  Could you send me an example of the output?

**Comment by gudongfeng** [comment]
@asolis 

```
<frame frameNumber="0">
    <box boxNumber="0" pointNumber:0="60.000000,166.000000" pointNumber:1="164.000000,166.000000" pointNumber:2="164.000000,339.000000" pointNumber:3="60.000000,339.000000"/>
</frame>
<frame frameNumber="1">
    <box boxNumber="0" pointNumber:0="60.000000,166.000000" pointNumber:1="164.000000,166.000000" pointNumber:2="164.000000,339.000000" pointNumber:3="60.000000,339.000000"/>
</frame>
<frame frameNumber="2">
    <box boxNumber="0" pointNumber:0="60.000000,166.000000" pointNumber:1="164.000000,166.000000" pointNumber:2="164.000000,339.000000" pointNumber:3="60.000000,339.000000"/>
</frame>
<frame frameNumber="3"/>
<frame frameNumber="4">
    <box boxNumber="0" pointNumber:0="61.000000,159.000000" pointNumber:1="153.000000,159.000000" pointNumber:2="153.000000,309.000000" pointNumber:3="61.000000,309.000000"/>
</frame>
<frame frameNumber="5">
    <box boxNumber="0" pointNumber:0="61.000000,159.000000" pointNumber:1="153.000000,159.000000" pointNumber:2="153.000000,309.000000" pointNumber:3="61.000000,309.000000"/>
    <box boxNumber="1" pointNumber:0="176.000000,105.000000" pointNumber:1="281.000000,105.000000" pointNumber:2="281.000000,293.000000" pointNumber:3="176.000000,293.000000"/>
</frame>
<frame frameNumber="6">
    <box boxNumber="0" pointNumber:0="61.000000,159.000000" pointNumber:1="153.000000,159.000000" pointNumber:2="153.000000,309.000000" pointNumber:3="61.000000,309.000000"/>
    <box boxNumber="1" pointNumber:0="176.000000,105.000000" pointNumber:1="281.000000,105.000000" pointNumber:2="281.000000,293.000000" pointNumber:3="176.000000,293.000000"/>
</frame>

```

**Comment by gudongfeng** [comment]
@asolis I just read the OpenCV [XML parser document](http://docs.opencv.org/2.4/doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.html). It seems that OpenCV cannot add the custom attribute to the XML node,

**Comment by asolis** [comment]
Yes, it seems you are right. At least there is no easy straight forward way to do it. Well I guess, we can keep your previous implementation. Just add the license of the xml software inside the code (assuming is open source :) )

**Pull request closed without merging**
